Remove criticality
robotframework/robotframework pull request #3662
Opened 2020-09-11 09:21 UTC by yanne

2020-09-11 13:13 UTC, mkorpela commented
Only 81 files 🤣

2020-09-12 06:38 UTC, mkorpela commented
Some notes about criticality use cases to check if we can cover these also in the future:

Static cases:
- [ ] _not-ready tag_ where a test/task is executed on automated system to ensure it almost works but should not affect the outcome)
- [ ]._flaky tag_ where a test/task is known or thought to have some problems and is under investigation

Dynamic cases:
- [ ] _environment-error tag_ where a test/task detects during execution that it can not be executed (SKIP case)

Any other?

2020-09-12 06:51 UTC, mkorpela commented
I think `--skiponfailure` will cover the two dynamic cases I had in mind

2020-09-14 22:05 UTC, pekkaklarck requested changes
Looks great but I found few smallish things that could be still addressed. Assuming tests pass, this PR is otherwise ready to be merged.

2020-09-14 22:05 UTC, pekkaklarck commented on src/robot/running/status.py
> +        self.exit.failure_occurred()
Should probably remove `critical_` from the method name.

2020-09-14 22:05 UTC, pekkaklarck commented on atest/robot/cli/runner/status_rc.robot
> +Non-zero RC when ests fail
ests -> tests

2020-09-15 11:02 UTC, yanne commented on src/robot/rebot.py
> +            LOGGER.warn("Command line option --xunitskipnoncritical has been deprecated.")
For some reason, when I added the deprecation warning there, the warning message was echoed twice to console. Something to do with `register_console_logger` I suppose.

2020-09-15 13:22 UTC, merged