Revert adding __eq__ methods to Statement class
robotframework/robotframework pull request #3832
Opened 2021-01-20 10:17 UTC by bhirsz

This should fix #3830

2021-01-20 10:19 UTC, bhirsz commented on utest/parsing/test_statements.py
> +        'Statements are not equal. %s (%s) != %s (%s)' % (st1, type_name(st1),
I could also import report_inequality from robot.asserts OR create new method inside robot asserts that will check if given condition is true.

2021-01-20 11:00 UTC, pekkaklarck requested changes

2021-01-20 11:00 UTC, pekkaklarck commented on utest/parsing/test_statements.py
> +from robot.utils.robottypes3 import type_name
Use `from robot.utils import type_name` instead. We generally import from package level when possible and the above isn't Python 2 compatible.

2021-01-28 13:11 UTC, fabioz commented
Is anything blocking this merge? -- I'd really like to have tests passing on the language server when running with the robotframework `master` again ;)

2021-02-03 10:15 UTC, merged

2021-02-03 10:16 UTC, pekkaklarck commented
The thing blocking merge was me forgetting about this. Great that @bhirsz reminded me on Slack and this made it to beta 2.