enhancement: JSON variable file support
robotframework/robotframework pull request #4542
Opened 2022-11-22 00:29 UTC by sunday2

Closes #4532

2023-02-13 19:49 UTC, pekkaklarck requested changes
Thanks for a great PR and sorry for reviewing taking so long. Only real issue I noticed in code and tests was that the extension wasn't case-insensitive as it should be, but I added also some other comments. Another thing to do is writing documentation. It can be done after merging this PR as well.

2023-03-04 12:38 UTC, sunday2 commented
> Thanks for a great PR and sorry for reviewing taking so long. Only real issue I noticed in code and tests was that the extension wasn't case-insensitive as it should be, but I added also some other comments. Another thing to do is writing documentation. It can be done after merging this PR as well.

2023-03-04 12:47 UTC, sunday2 commented
> Thanks for a great PR and sorry for reviewing taking so long. Only real issue I noticed in code and tests was that the extension wasn't case-insensitive as it should be, but I added also some other comments. Another thing to do is writing documentation. It can be done after merging this PR as well.

2023-03-05 02:39 UTC, sunday2 commented on src/robot/variables/filesetter.py
> +        with io.open(path, encoding='UTF-8') as stream:
Thanks for the explain and I will not change both of them in this PR.

2023-03-05 02:44 UTC, sunday2 commented
> 

Thank you for the review and all the comments, I have updated the code. If there is any other concern, pls don't hesitate to let me know. For writing document, maybe I need to spend some time on studying how to write it.

2023-03-05 02:46 UTC, sunday2 commented
> Thanks for a great PR and sorry for reviewing taking so long. Only real issue I noticed in code and tests was that the extension wasn't case-insensitive as it should be, but I added also some other comments. Another thing to do is writing documentation. It can be done after merging this PR as well.

Thank you for the review and all the comments, I have updated the code. If there is any other concern, pls don't hesitate to let me know. For writing document, maybe I need to spend some time on studying how to write it.

![image](https://user-images.githubusercontent.com/20227068/222938894-15ea948f-3e84-4947-85c1-1b58d3acd282.png)

2023-03-10 23:23 UTC, merged

2023-03-10 23:25 UTC, pekkaklarck commented
Thanks for a great PR! I can write the documentation myself, I think it can mainly refer to existing YAML variable file documentation so it's a small task.