Listener version default - #4910
robotframework/robotframework pull request #4916
Opened 2023-10-28 18:22 UTC by mitzeee

PR to implement issue #4910.

2023-11-01 13:52 UTC, pekkaklarck requested changes
In addition to the changes mentioned in separate comments, also the User Guide needs to be updated.

2023-11-01 13:52 UTC, pekkaklarck commented on atest/robot/output/listener_interface/unsupported_listener_version.robot
> -
A new test is needed to make sure using a listener without `ROBOT_LISTENER_API_VERSION` is possible.

2023-11-01 13:52 UTC, pekkaklarck commented on src/robot/output/listeners.py
> +            "Sicne 7.1, Listener API version is by default considered to be V3 unless explicitly mentioned as V2"
No need for this kind of a comment. If it was needed, it should be a normal comment starting with a `#`.

2023-11-01 13:58 UTC, pekkaklarck commented
Thanks for a PR! As explained in my review, some changes are still needed. In addition to that, the listener code is currently in flux and there will be conflict. PR #4920 ought to contain all changes related to this, so it's a good idea to wait until it is merged (which should happen latest tomorrow).

2023-11-02 14:39 UTC, pekkaklarck commented
PR #4920 is now in and there's indeed a conflict. Let us know @mitzeee are you interested to continue with this PR. If not, we can make required changes also ourselves.

2023-11-02 17:38 UTC, mitzeee commented
@pekkaklarck Thanks for the comments. I will definitely make the changes and push.
* New test
* Comment correction
* User-guide update

2023-11-27 12:15 UTC, closed without merging

2023-11-27 12:15 UTC, pekkaklarck commented
I need this functionality now and will implement it myself. Thanks anyway!