feat: Add support for "week" as a valid unit of time in time strings
robotframework/robotframework pull request #5136
Opened 2024-05-30 21:17 UTC by ChristopherJHart

This PR fixes #5135 and stands as a potential implementation for a "week" as a valid unit of time in a time string.

Documentation was updated to indicate that a "week" is now a valid unit of time. Furthermore, unit tests were also added to ensure backwards compatibility. I should call out that one of the unit tests ensuring invalid formats raise an exception needed to be modified from `w` to `y` in order to pass. I *think* the intent of this unit test was to ensure that units of time must be sorted (e.g. days, then hours, then minutes, etc.) and not reversed/arbitrary (minutes, then weeks, then days, etc.). However, if I misinterpreted that and need to modify the unit tests somehow, let me know!

2024-05-31 15:11 UTC, pekkaklarck requested changes
Changes look very good. Few things that should be done:

- It should be mentioned in the docs that `week` is new in RF 7.1. There could be a separate note about that or the list item with `weeks`, `week` and `w` could have something like `(New in Robot Framework 7.1)` at the end.
- The time format is explained also in a User Guide appendix. The new functionality should be explained there as well, along with a note about it being new in 7.1. The file to edit is `doc/userguide/src/Appendices/TimeFormat.rst`.
- It would be good to have this covered also be acceptance tests. Not sure are new tests needed, but some of the DateTime library tests could be modified to use `week`. For example at atest/testdata/standard_libraries/datetime/convert_time_input_format.robot.

2024-05-31 17:28 UTC, ChristopherJHart commented
Requested changes have been implemented! Sorry about not originally including the acceptance tests - I totally glossed over the fact the `atest` directory exists 😅

2024-07-03 14:20 UTC, pekkaklarck approved these changes

2024-07-03 14:22 UTC, merged

2024-07-03 14:22 UTC, pekkaklarck commented
Thanks for an excellent PR @ChristopherJHart!