Added GROUP syntax
robotframework/robotframework pull request #5275
Opened 2024-11-22 12:45 UTC by Snooz82

Implements #5257

2024-11-30 23:28 UTC, Snooz82 commented
@pekkaklarck I think i am done.
The one open thing i am aware of is the User Guide.
I would ask you to write that, then i can focus on the certs and the exam question.

Let me know if i shall do changes.

2024-12-13 15:07 UTC, pekkaklarck commented on src/robot/model/control.py
> +        visitor.visit_while(self)
Should be `visit_group`. It seems tests for visitor interface are missing.

2024-12-13 15:21 UTC, pekkaklarck requested changes
Looks excellent! There we few small things to fix (most importantly `visit_while` -> `visit_group`) that I mentioned in separate comments. In addition to that, these things need to be still handled:

- Investigate why tests fail. They seem to have passed initially, but now after I fixed conflicts with master there are failures. Could be due to changes I've done.
- Add tests for GROUP with templates. This likely requires some further code fixes too. Can be done after merging the PR, but needs to be done before the beta.
- Write documentation. Can be done after beta and even after the rc.

I can take care of fixing these issues, but I won't have time for that right now. If you @Snooz82 want to do something, we can coordinate on Slack.

2024-12-13 21:31 UTC, pekkaklarck commented on doc/schema/result.xsd
> +    </xs:complexType>
Resolved.

2024-12-13 21:33 UTC, pekkaklarck commented on src/robot/parsing/parser/blockparsers.py
> +
Resolved.

2024-12-13 21:33 UTC, pekkaklarck commented on src/robot/model/control.py
> +        visitor.visit_while(self)
Resolved.

2024-12-13 21:35 UTC, pekkaklarck commented
Test failures were due to my changes to master. I've fixed all minor issues that I noticed. Assuming tests pass, I'll merge this and then handle templates afterwards.

2024-12-13 21:46 UTC, merged